---
title: "Project Proposal"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data

We will use tweets and news headlines about publicly traded stocks in the US stock market from this [source](https://www.kaggle.com/vivekrathi055/sentiment-analysis-on-financial-tweets) for the model building. Data were collected from CNBC, Bloomberg, Twitter, MarketWatch, Bitcoin, etc.

- Genre: social media and news media
- Language: English only
- Language Style: both formal and informal language
- Size: corpus consists 28440 tweets and news headlines, all of them are already annotated for sentiment orientation. We will divide the dataset into train, development and test sets for the model building. We will save the data in a .csv file.


## Engineering

- Computing Infrastructure: we will conduct data wrangling, data preprocessing, and initial model building on our personal computers, run and test deep learning models on Google Colab.
- DL-NLP method: we will employ Convolutional Neural Network(CNN) for Sentiment Analysis. We will probably employ Bidirectional Encoder Representations fromTransformers(BERT) to build another sentiment analysis model if we have enough time after the first model is completed.  
- Framework: the [Convolutional Neural Network tutorial](https://github.ubc.ca/MDS-CL-2019-20/COLX_585_trends_students/blob/master/labs/Lab1/cnn_text.ipynb) from week 1 is the codebase we will start off with. 

## Previous Works
- [BERT for Stock Market Sentiment Analysis](https://ieeexplore-ieee-org.ezproxy.library.ubc.ca/stamp/stamp.jsp?tp=&arnumber=8995193). The purpose and methods used in this article could be referenced by us during the model building process.  

## Evaluation

We will use macro F1 score to evaluate the model performance.
